include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule

